name: Build DBB CLI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: ./autogen.sh
./configure --enable-debug --with-gui=qt5 --enable-libusb
make
sudo make install
          
      - name: Build Project
        run: make
